// Generated by scripts/sync-about-changelog.mjs — do not edit by hand.
// Source: CHANGELOG.md (updated when changeset version runs; build runs this script).

export const RECENT_UPDATES: { version: string; entries: string[] }[] = [
  {
    "version": "0.23.6",
    "entries": [
      "TECH-6005 cleanup, optimize misc"
    ]
  },
  {
    "version": "0.23.5",
    "entries": [
      "Use a smaller app logo on mobile (narrow viewports); desktop size unchanged."
    ]
  },
  {
    "version": "0.23.4",
    "entries": [
      "Fix Cancel on edit plan in mobile: use Link so navigation works when not dirty; when dirty, prevent default and show discard confirm. Place Cancel at bottom left of the form and Save at bottom right; ensure 44px touch target for Cancel."
    ]
  },
  {
    "version": "0.23.3",
    "entries": [
      "Disable save and delete buttons while the form action is in progress to prevent duplicate tasks or records when there is a delay (e.g. on mobile). Uses useFormStatus for in-form buttons and onSubmit/onStateChange for the edit-task external Save button."
    ]
  },
  {
    "version": "0.23.2",
    "entries": [
      "Show trash icon for delete buttons on mobile: task delete, plan delete (already present), supply item delete. Desktop still shows text label."
    ]
  },
  {
    "version": "0.23.1",
    "entries": [
      "Enforce 4.2 MB maximum file size for task attachments. Client shows a translated message when file exceeds limit; API rejects oversized uploads."
    ]
  },
  {
    "version": "0.23.0",
    "entries": [
      "New Actions page at `/actions` showing urgent and upcoming tasks (urgency 6+ or due within three days). Logo now links to Actions instead of Plans. Overdue tasks show an alarm icon; list supports edit, mark done, and add to calendar.",
      "Reduce navbar icon size and highlight area on mobile; pull nav icons closer to the logo and to each other. Desktop unchanged."
    ]
  },
  {
    "version": "0.22.1",
    "entries": [
      "TECH-0060 Fix edit button on supplies list"
    ]
  },
  {
    "version": "0.22.0",
    "entries": [
      "TECH-0058: bundle analysis, lazy-load editor, remove unused deps and dead code. Add `npm run analyze` (Next.js bundle analyzer), lazy-load TaskContentEditor in TaskForm, remove unused devDependencies and unused `formatPlanStatus`; update roadmap docs."
    ]
  },
  {
    "version": "0.21.2",
    "entries": [
      "Apply dark mode to all popout edit and add forms (task add/edit, supply edit, share plan, delete plan, discard confirm modals) so dialogs and form fields respect the app theme."
    ]
  },
  {
    "version": "0.21.1",
    "entries": [
      "TECH-6003 branch report"
    ]
  },
  {
    "version": "0.21.0",
    "entries": [
      "Plans list and plan form: show plan color as a small flag icon (rectangular flag on pole) instead of circles. Add black, pink, and silver as flag color options. All new strings translated (en, fr, pidgin)."
    ]
  },
  {
    "version": "0.20.6",
    "entries": [
      "Plan form: label the 1–7 scale \"Urgency\" (matching tasks) in all locales. Urgency bubbles already use short labels on mobile for one-line layout."
    ]
  },
  {
    "version": "0.20.5",
    "entries": [
      "Add top padding above the logo in the app header on mobile (e.g. Pixel 8) so the navbar has visible margin."
    ]
  },
  {
    "version": "0.20.4",
    "entries": [
      "Move save task button to the bottom of the edit task form in the dialog (below attachments, export, mark done, and delete)."
    ]
  },
  {
    "version": "0.20.3",
    "entries": [
      "Remove \"Remove this task permanently.\" text from edit-task delete section; delete button is sufficient."
    ]
  },
  {
    "version": "0.20.2",
    "entries": [
      "Fix toast when marking a task as done inside a plan: show \"Marked done\" / \"Task completed\" instead of \"Task restored\"."
    ]
  },
  {
    "version": "0.20.1",
    "entries": [
      "Task form: use dark black text for task name and description fields. When adding a new task with a name but no description, default the description to the entered name (server-side)."
    ]
  },
  {
    "version": "0.20.0",
    "entries": [
      "Add dark mode: theme setting (Light / Dark / System) in Settings, persisted via cookie. App shell, settings, and login use dark-aware styles so users can spare their eyes in low light."
    ]
  },
  {
    "version": "0.19.0",
    "entries": [
      "Add public share links for plans. Plan owners can generate a shareable link from the plan detail page; anyone with the link can view the plan and its tasks in read-only form and, when allowed, mark tasks done or restore them. Only explicitly shared plans are exposed; invalid or expired links show a single generic message."
    ]
  },
  {
    "version": "0.18.0",
    "entries": [
      "Add Facebook login as an authentication option.",
      "Mobile and nav UI improvements: logo top margin on mobile; larger nav icons and currency icon for supplies; illuminated lightbulb; help/about/settings/sign-out icons and label in hamburger menu; larger, bolder nav badges with tighter spacing; mobile nav bubbles overlap slightly to remove gaps; supplies icon nudged left on mobile. Input contrast: text and placeholders use darker colors (text-zinc-900, placeholder:text-zinc-500) across PlanForm, PlanSupplyList, SupplyItemForm, SharePlanButton, TaskContentEditor, NewPlanSection."
    ]
  },
  {
    "version": "0.17.0",
    "entries": [
      "Add optional Facebook login: when `AUTH_FACEBOOK_ID` and `AUTH_FACEBOOK_SECRET` are set, the login page shows \"Continue with Facebook\" and NextAuth uses the Facebook provider. Documented in README (Facebook app setup, redirect URI)."
    ]
  },
  {
    "version": "0.16.0",
    "entries": [
      "Add per-plan Supplies (tab on plan detail) with add/edit/delete supply items including quantity, status, optional price/link/description, plus a central Supplies page that aggregates items by plan with per-plan totals and inline editing."
    ]
  },
  {
    "version": "0.15.0",
    "entries": [
      "Add prebuilt plan templates on new plan page: \"Start from\" dropdown with Empty, Project launch, and Trip planning. Selecting a template pre-fills plan name, goal, and default task titles. Template names and task titles translated (en, fr, pidgin)."
    ]
  },
  {
    "version": "0.14.0",
    "entries": [
      "Improve login screen: add value-proposition headline (\"Plans and tasks, shared\"), three benefit bullets (plans and tasks in one place, share with others, works in your language), and responsive layout. All copy in i18n (en, fr, pidgin)."
    ]
  },
  {
    "version": "0.13.0",
    "entries": [
      "Add Help and About pages: in-app /help (how to use tasks and plans, recent updates, link to changelog) and /about (app version from package.json, contributors). Nav includes Help and About links; all copy translated (en, fr, pidgin)."
    ]
  },
  {
    "version": "0.12.0",
    "entries": [
      "TECH-1001 Data handling optimizations: cache revalidation on task delete, shared format/task service layer, plan create/update transactions and createMany, task API parity (planId/urgency, GET includes), pagination for tasks/plans/plan-detail tasks, Prisma dev logging, blob cleanup on attachment/task delete, GET /api/plans."
    ]
  },
  {
    "version": "0.11.1",
    "entries": [
      "Added \"Print checklist\" on plan detail: links to a print view that shows plan name, printed date, and unfinished tasks (sorted by priority then due date). Print view has a Print button and @media print hides chrome so only the checklist is printed."
    ]
  },
  {
    "version": "0.11.0",
    "entries": [
      "Discard-changes confirmation for new and edit plan forms (custom dialog when leaving with unsaved data).",
      "Plan \"color\" is now shown as \"Flag\" in the UI: form label is \"Flag (optional)\" with emoji per option; plans list shows a flag emoji next to the plan name when set."
    ]
  },
  {
    "version": "0.10.5",
    "entries": [
      "On mobile, task rows now show shorter dates (e.g. \"Mar 8\") and plan names truncate; status button (Mark done / Restore) is explicitly ordered first before Edit on both plan detail and tasks page."
    ]
  },
  {
    "version": "0.10.4",
    "entries": [
      "Plans list now shows task completion as a segment bar (green for completed, grey for incomplete), with \"X of Y\" text and an accessible aria-label."
    ]
  },
  {
    "version": "0.10.3",
    "entries": [
      "On the plan detail page, the tasks section header (with \"Add task\") is now sticky on mobile so it stays in view when scrolling the task list."
    ]
  },
  {
    "version": "0.10.2",
    "entries": [
      "New task form: due date is blank by default instead of tomorrow 9am."
    ]
  },
  {
    "version": "0.10.1",
    "entries": [
      "Pidgin: rename \"Waka\" to \"Work\" for tasks label to avoid offensive term."
    ]
  },
  {
    "version": "0.10.0",
    "entries": [
      "Plan form: urgency and percent complete moved to top; percent complete is a slider. Plans list shows progress bar graphic for percent complete."
    ]
  },
  {
    "version": "0.9.3",
    "entries": [
      "Plan edit page and form are more mobile friendly: reduced padding on small screens, full-width inputs, stacked layout for add-task row, and resizable textareas."
    ]
  },
  {
    "version": "0.9.2",
    "entries": [
      "Logo no longer shows off-center due to transparent padding: image is clipped with object-cover and header margin compensation removed."
    ]
  },
  {
    "version": "0.9.1",
    "entries": [
      "Plans page task list now shows incomplete tasks first and completed tasks at the bottom, so tasks are displayed more prominently and completed items no longer appear above active work."
    ]
  },
  {
    "version": "0.9.0",
    "entries": [
      "After creating an invite link, a new \"Email invite\" button appears beside the copy button. It opens the user's mail client with a pre-filled subject (e.g. \"You're invited to plan: [plan name]\") and body containing plan details and the invite link, encouraging the recipient to open the plan. All copy is translated (en, fr, pidgin)."
    ]
  },
  {
    "version": "0.8.3",
    "entries": [
      "Image placement for plan image URL: plan images (when added as URL) are now centered and no longer cropped; the bottom of the picture is no longer cut off. Plan form preview and plan list use object-contain with centered alignment inside a flex container."
    ]
  },
  {
    "version": "0.8.2",
    "entries": [
      "Mobile task date and plan display: deadline, added/completed date, and associated plan are shown one per line on mobile with simplified short dates (e.g. \"Mar 8, 2026\"); status (Mark done / Restore) button is to the left of the Edit button on both the tasks list and the plan detail page. TaskActionButton now supports an optional planId for plan page revalidation."
    ]
  },
  {
    "version": "0.8.1",
    "entries": [
      "Mobile add/edit task form: when opening the edit task dialog from the task list or from inside a plan, the dialog is now scrolled into view so users do not have to scroll up to see the form (fixes tasks further down the list being off-screen)."
    ]
  },
  {
    "version": "0.8.0",
    "entries": [
      "Add task dialogue from plans page: plan detail page now shows an \"Add task\" button that opens the full add-task dialog with the current plan pre-selected, so users can add tasks directly to the plan without adding then saving separately. Plan detail revalidates when a task is added to that plan."
    ]
  },
  {
    "version": "0.7.3",
    "entries": [
      "Document bulk task → PR pipeline in AGENTS.md: when tasks are provided in JSON form, create one PR per task with incrementing tech IDs, implement or document future work, add detailed changesets, and optionally skip local build/typecheck for speed."
    ]
  },
  {
    "version": "0.7.2",
    "entries": [
      "Fix task edit dialog and other modals so they appear at the top of the viewport and are scrollable, avoiding the need to scroll the page to see the form when there are many tasks."
    ]
  },
  {
    "version": "0.7.1",
    "entries": [
      "Ensure French and Nigerian Pidgin translations are shown for all app text. Added TranslationsProvider and useTranslations for client components; expanded i18n with all user-facing strings and wired every page and component to use them."
    ]
  },
  {
    "version": "0.7.0",
    "entries": [
      "Add invite-by-link for plans: plan owner can create a secure invite link from the plan detail page. Anyone with the link can open it, sign in (or sign up), and be added to the plan as a viewer. Includes plan sharing by email and read-only view for shared users. Login page respects callbackUrl so invite flow redirects back after sign-in."
    ]
  },
  {
    "version": "0.6.0",
    "entries": [
      "Share plans with another user by email. Plan owner can use \"Share\" on the plan detail page; the other user (must have signed in to Plan 2026 with that email) sees the plan in their list as \"Shared with me\" and can view it read-only."
    ]
  },
  {
    "version": "0.5.0",
    "entries": [
      "Add file upload for tasks: attach files to a task from the edit dialog. Files are stored in Vercel Blob (or compatible). Requires `BLOB_READ_WRITE_TOKEN` when deployed. Task attachments are listed in the edit dialog with links and remove action.",
      "Add language preference: users can choose English, French (Français), or Nigerian Pidgin in Settings. Nav and settings labels use the selected language. Preference is stored in a cookie.",
      "Fix add-task dialog on mobile: keep form visible on load by aligning dialog to top and making content scrollable instead of centered off-screen.",
      "Improve mobile layout for task and plan lists: stack list rows on small screens so content and actions wrap correctly, add break-words for metadata lines, and fix plan name truncation.",
      "Plans page: show incomplete tasks first, completed tasks at the bottom of the task list.",
      "Add SEO improvements: richer metadata (Open Graph, Twitter card, description), sitemap.xml, and robots.txt. Public pages remain indexable; app routes are disallowed for crawlers."
    ]
  },
  {
    "version": "0.4.0",
    "entries": [
      "Add export to JSON for plans and tasks. Export buttons appear on the tasks list, plans list, plan edit page, and in the task edit dialog. Exported JSON includes source and schema hints for debugging and for AI/automation to ingest when extending the app."
    ]
  },
  {
    "version": "0.3.0",
    "entries": [
      "Plans now support an \"On hold\" status in addition to draft, started, completed, and abandoned. On-hold plans appear in the main list (they are not archived) and use a violet pill in the UI.",
      "Plans page now matches tasks: nav uses #plans/#tasks, list has refresh and \"Show completed/abandoned\" toggle, and each plan row has Edit and a status dropdown. Plan detail page lists tasks with an edit modal so you can edit tasks without leaving the plan."
    ]
  },
  {
    "version": "0.2.1",
    "entries": [
      "Security hardening: require AUTH_SECRET in production (dev uses random secret), CUID validation for task IDs, rate limiting on task API routes, CSP and security headers, generic error messages for task operations, reduced Prisma logging, and HTML sanitizer no longer allows `<u>`. Docs updated for CSRF and secret rotation."
    ]
  },
  {
    "version": "0.2.0",
    "entries": [
      "Add Plans: list plans at /plans, create at /plans/new, edit at /plans/[id]. Plans have name, status (draft/started/completed/abandoned), priority 1–7, percent completed, dates, optional goal/notes/color/image URL. Tasks can be linked to a plan; task list shows plan link when set."
    ]
  },
  {
    "version": "0.1.5",
    "entries": [
      "Fix Google Calendar reconnects after permissions are revoked by forcing fresh Google consent and showing a reconnect action in Settings.",
      "Replace the Settings text tab with a gear icon in the header and move it beside the signed-in email address.",
      "TECH-0008 Fix build"
    ]
  },
  {
    "version": "0.1.4",
    "entries": [
      "Add a branded Plan 2026 logo to the app header and sign-in screen for a more polished identity."
    ]
  },
  {
    "version": "0.1.3",
    "entries": [
      "Rename the dashboard tab to Tasks with a remaining-count badge, move completed items into a toggle on the main tasks page, switch task creation to a modal, and use `/tasks` as the canonical route.",
      "Google sign-in now reuses previously granted Google scopes when available, preserves an existing Google refresh token when later sign-ins do not return a new one, adds an authenticated settings page where users can disconnect Google Calendar access, keeps tasks linked to a single Google Calendar event instead of creating duplicates on repeated adds, lets users edit or delete task details from the task editor instead of from the main list, and adds color-coded task urgency with highest-priority tasks sorted first plus a manual reload button on the tasks page."
    ]
  },
  {
    "version": "0.1.2",
    "entries": [
      "Clean up task auth plumbing and editor syncing, use the configured app font consistently, and clarify that PostgreSQL is used for both local and deployed environments."
    ]
  },
  {
    "version": "0.1.1",
    "entries": [
      "Refresh the tasks and login styling with blue and red accents, active navigation states, and updated app metadata."
    ]
  }
];
